spring.application.name=zorrobpm-app

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/zorrobpm-db}
spring.datasource.username=${DB_USERNAME:zorrodev}
spring.datasource.password=${DB_PASSWORD:zorrodev}

app.filesDir=${APP_FILES_DIR:${user.home}/.zorrobpm/files}

spring.rabbitmq.addresses=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:zorrodev}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:zorrodev}

spring.rabbitmq.requested-heartbeat=10
spring.rabbitmq.listener.simple.auto-startup=true
spring.rabbitmq.listener.simple.missing-queues-fatal=true

server.forward-headers-strategy=framework

spring.ai.mcp.server.name=zorrobpm-mcp
spring.ai.mcp.server.protocol=streamable
