package com.zorrodev.bpm.engine.bpmn.model;

public enum BpmnElementType {
    EVENT,
    SERVICE_TASK,
    SEND_TASK,
    RECEIVE_TASK,
    USER_TASK,
    START_EVENT,
    END_EVENT,
    EXCLUSIVE_GATEWAY,
    PARALLEL_GATEWAY,
    SEQUENCE_FLOW,
    MESSAGE_CATCH_EVENT,
    TIMER_CATCH_EVENT,
    MESSAGE_THROW_EVENT,
    INTERMEDIATE_CATCH_EVENT,
    INTERMEDIATE_THROW_EVENT,
    MESSAGE_START_EVENT,
    TIMER_START_EVENT,
    CALL_ACTIVITY
}
